name: ci

on:
  push:
    branches:
      - master

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      -
        name: checkout
        uses: actions/checkout@v1
      -
        name: setup node
        uses: actions/setup-node@v1
        with:
          node-version: 10.x
      - run: npm install
      - run: npm run lint:fix
      - run: npm run test
